version: "3.1"

services:
    cassandra:
        image: cassandra:3.11

    cadence:
        image: ubercadence/server:0.5.1
        environment:
            - "LOG_LEVEL=debug,info"
            - "CASSANDRA_SEEDS=cassandra"
        volumes:
            - ./cadence.yml:/go/src/github.com/uber/cadence/config/docker_template.yaml
        ports:
            - "7933:7933"
            - "7934:7934"
            - "7935:7935"
        depends_on:
            - cassandra

    cadence-web:
        image: ubercadence/web:3.2.2
        environment:
            - "CADENCE_TCHANNEL_PEERS=cadence:7933"
        ports:
            - "8088:8088"
        depends_on:
            - cadence
